FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG OPENAI_API_KEY
ENV OPENAI_API_KEY=$OPENAI_API_KEY

WORKDIR /app

COPY ../requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ../src/ ./src/

EXPOSE 8501
CMD ["streamlit", "run", "src/ui_streamlit.py"]